schemaBasePath: ./schemas/

# Files to be generated. 
# Available: [json] [yaml] [json, yaml]
contentTypes: [json]

logLevel: info
shouldGenerateExample: true

shouldSymlinkExtensionless: false
shouldSymlinkLatest: false
