name: Build current files not in main and commit
on: 
  push:
    branches:
      - '*'
      - '!main'

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Confirm configuration files used
        working-directory: ./
        run: |
          cat .jsonschema-tools.yaml
          cat test/jsonschema/repository.test.js

      - name: Fetch repo
        working-directory: ./
        run: git fetch

      - name: Build current files different than main branch
        working-directory: ./  
        run:  npm run build-modified-main

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'Schema(s) build and commit via GH action.'
          add: '*'
